apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
  labels:
    app: debug-task-app
data:
  default.conf: |
    server {
        listen 8081;

        location / {
            proxy_pass http://127.0.0.1:8080;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        }

        location /health {
            proxy_pass http://127.0.0.1:8080/health;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        }

        location /uploads {
            alias /uploads;
            autoindex on;
            allow all;
        }
    }

